[package]
name = "subpub_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["net", "macros", "rt-multi-thread", "sync", "time"] }
log = "0.4"
env_logger = "0.10"
dashmap = "5.5"
